# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         MySQL-Handler
version:      1.8
version_from: lib/MySQL/Handler.pm
installdirs:  site
requires:
    CGI::Carp:                     0
    CGI::Util:                     0
    Class::Struct:                 0
    DBD::MySQL:                    0
    DBI:                           0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
